version: 2
updates:
  # Конфигурация для обновления GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # Проверка обновлений еженедельно
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    rebase-strategy: "auto"

  # Конфигурация для обновления NuGet пакетов
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct" # Только прямые зависимости
    labels:
      - "dependencies"
      - "nuget"
    versioning-strategy: "increase"
