<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>img\Antenna.ico</ApplicationIcon>
    <ImplicitUsings>true</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ExcludeFilesFromDeployment Include="cs\**;de\**;es\**;fr\**;it\**;ja\**;ko\**;pl\**;pt-BR\**;tr\**;zh-Hans\**;zh-Hant\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="img\Radar.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="img\Antenna.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="img\Radar.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MathCore" Version="0.0.93.2" />
    <PackageReference Include="MathCore.WPF" Version="0.0.48.2" />
    <PackageReference Include="OxyPlot.Contrib.Wpf" Version="2.1.2" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.1.2" />
  </ItemGroup>  

  <ItemGroup>
    <ProjectReference Include="..\AntennaLib\AntennaLib.csproj" />
  </ItemGroup>

  <Target Name="RemoveUnwantedCultures" AfterTargets="Publish">
    <ItemGroup>
      <UnwantedCultures Include="cs;de;es;fr;it;ja;ko;pl;pt-BR;tr;zh-Hans;zh-Hant" />
    </ItemGroup>
    <Exec Command="for %%c in (@(UnwantedCultures)) do rmdir /s /q $(PublishDir)%%c" />
  </Target>

</Project>